# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Document\User:
            algorithm:        sha512
            encode_as_base64: true
            iterations:       10

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        secure_api_provider:
            id: app.user.provider

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main:
            #anonymous: ~
           # pattern: ^/
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

        register:
            pattern:  ^/api/register$
            security: false

        login:
            pattern:  ^/api/login$
            security: false

        session:
            pattern:  ^/api/session$
            security: false

        api:
            pattern: ^/api/.*
            stateless: true
            secure-api: true
            anonymous: true
            provider: secure_api_provider