# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
  #rest_api.version_listener:
   # class: AppBundle\Listener\ApiVersionListener
   # tags:
   #   - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10000}
   # calls:
   #   - [setSerializer, ["@serializer"]]

  manager.comment:
    class : AppBundle\Service\CommentManager
    arguments: [@doctrine.orm.entity_manager]