users :
  type: rest
  resource: "AppBundle:User"
  name_prefix:  api_

Properties :
  type: rest
  resource: "AppBundle:Properties"
  name_prefix:  api_

Places :
  type: rest
  resource: "AppBundle:Places"
  name_prefix:  api_

Auth :
  type: rest
  resource: "AppBundle:Auth"
  name_prefix:  api_
