users :
  type: rest
  resource: "AppBundle:User"
  name_prefix:  api_

organisations :
  type: rest
  resource: "AppBundle:Organisation"
  name_prefix:  api_

Properties :
  type: rest
  resource: "AppBundle:Properties"
  name_prefix:  api_

Tags :
  type: rest
  resource: "AppBundle:Tags"
  name_prefix:  api_
